"""empty message

Revision ID: f4fe1cff8b05
Revises: 66abdb93620c
Create Date: 2022-06-01 01:27:08.783955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4fe1cff8b05'
down_revision = '66abdb93620c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('comments', sa.Column('post_id', sa.Integer(), nullable=False))
    op.drop_constraint('comments_user_fkey', 'comments', type_='foreignkey')
    op.drop_constraint('comments_post_fkey', 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'posts', ['post_id'], ['id'])
    op.create_foreign_key(None, 'comments', 'users', ['user_id'], ['id'])
    op.drop_column('comments', 'user')
    op.drop_column('comments', 'post')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('post', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('comments', sa.Column('user', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key('comments_post_fkey', 'comments', 'posts', ['post'], ['id'])
    op.create_foreign_key('comments_user_fkey', 'comments', 'users', ['user'], ['id'])
    op.drop_column('comments', 'post_id')
    op.drop_column('comments', 'user_id')
    # ### end Alembic commands ###
